#!/usr/bin/env bash

(
  list_source_dotfiles() { ls | grep -v 'make_links' | grep -v 'README.md' ;}

  target_full_path() { echo ~/.$1; }

  source_full_path() { find `pwd` -name $1; }

  make_symbolic_link() { ln -s $SOURCE $TARGET; }

  list_source_dotfiles | while read file; do
    SOURCE=$(source_full_path $file)
    TARGET=$(target_full_path $file)

    if [[ ! -e $TARGET ]]; then
      make_symbolic_link
      echo "$TARGET: symbolic link created"
    elif [[ -L $TARGET && $(readlink $TARGET) == $SOURCE ]]; then
      echo $TARGET: ok
    else
      echo $SOURCE
      echo $TARGET: NOT ok
    fi
  done

 )
